### ISSUE TITLE
Removing listener during dispatch skips next listener

### ISSUE THREAD

**Issue by xDranik** [krasimir/EventBus#11]
Hey there!

I found that removing a listener while the event for that listener is being dispatched can cause the next listener to not get called.

Example:
```js
const EventBus = require('eventbusjs');

const listener1 = () => {
  console.log('I get logged!');
  EventBus.removeEventListener('unlock', listener1);
};

const listener2 = () => {
  console.log('I do not get logged :(');
};

EventBus.addEventListener('unlock', listener1);
EventBus.addEventListener('unlock', listener2);

EventBus.dispatch('unlock');
```

This is caused by `removeEventListener` removing from the same array that `dispatch` is referencing: https://github.com/krasimir/EventBus/blob/master/src/EventBus.js#L42 and https://github.com/krasimir/EventBus/blob/master/src/EventBus.js#L76.

This can be solved by slicing the listeners array before iterating over it. That way `removeEventListener` overriding `this.listeners` will not affect `dispatch`.

**Comment by krasimir** [comment]
@xDranik #10 is now merged. Let me know if the latest version fixes your issue.

**Comment by krasimir** [comment]
`0.2.0` released.

**Comment by xDranik** [comment]
@krasimir thanks!
